from config.default import *

DEFAULT_STORAGE_ENDPOINT = os.getenv('DEFAULT_STORAGE_END_POINT')
DEFAULT_STORAGE_CREDENTIAL = os.getenv('DEFAULT_STORAGE_CREDENTIAL')
LOGGERURL = os.getenv('LOGGER_URL')
K8S_CONFIG = ""
